// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8aUm_MXKje6SN1m0xqjCj1s-O8NId2g',
    appId: '1:626633218454:android:9ce57102eb543faffee5b7',
    messagingSenderId: '626633218454',
    projectId: 'ub-panic-button',
    databaseURL: 'https://ub-panic-button-default-rtdb.firebaseio.com',
    storageBucket: 'ub-panic-button.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRp_zT6Nw6QmWO3UanAdoGtaosOuUvrg',
    appId: '1:626633218454:ios:c030d3970ffcf537fee5b7',
    messagingSenderId: '626633218454',
    projectId: 'ub-panic-button',
    databaseURL: 'https://ub-panic-button-default-rtdb.firebaseio.com',
    storageBucket: 'ub-panic-button.appspot.com',
    iosClientId: '626633218454-4e93uputefeb3489v0lp9j6r7956quav.apps.googleusercontent.com',
    iosBundleId: 'tech.islandexecs.mingoesmobile.mingoesmobile',
  );
}
