class News {
  String? headline, story;

  News(this.headline, this.story);
}

  List<News> newsStories = [
    new News("Interesting Headline",
        "Suspendisse potenti. Nunc lacus dui, consequat ut libero sed, iaculis commodo velit. Nunc porttitor quam non metus ultrices, a mattis sem efficitur. Praesent nec sem magna. Mauris commodo erat quis rhoncus venenatis. Maecenas urna tortor, consectetur id est ut, pulvinar vulputate urna. Fusce at condimentum diam, ac scelerisque libero. Pellentesque dictum neque at arcu laoreet, vitae suscipit dolor rhoncus. Fusce ligula est, interdum nec finibus ac, tincidunt nec massa. Vestibulum vitae leo felis. Suspendisse dui nulla, condimentum id faucibus sed, feugiat at massa. Duis in mauris arcu. Sed luctus justo ut est tempor mollis. In augue ligula, consectetur nec interdum vel, convallis quis tortor. Curabitur lobortis neque non porttitor faucibus. Aliquam erat volutpat. Mauris euismod pellentesque rutrum. Etiam nec consequat diam. Vivamus aliquet ornare ligula. Praesent nec sagittis sapien, vitae convallis massa. Praesent eu convallis magna, non interdum leo. Praesent dui lacus, tempus eget tellus id, rhoncus rutrum magna. Vivamus augue odio, vulputate ut dapibus blandit, iaculis non mi."),
    new News("Cool Title",
        "Suspendisse potenti. Nunc lacus dui, consequat ut libero sed, iaculis commodo velit. Nunc porttitor quam non metus ultrices, a mattis sem efficitur. Praesent nec sem magna. Mauris commodo erat quis rhoncus venenatis. Maecenas urna tortor, consectetur id est ut, pulvinar vulputate urna. Fusce at condimentum diam, ac scelerisque libero. Pellentesque dictum neque at arcu laoreet, vitae suscipit dolor rhoncus. Fusce ligula est, interdum nec finibus ac, tincidunt nec massa. Vestibulum vitae leo felis. Suspendisse dui nulla, condimentum id faucibus sed, feugiat at massa. Duis in mauris arcu. Sed luctus justo ut est tempor mollis. In augue ligula, consectetur nec interdum vel, convallis quis tortor. Curabitur lobortis neque non porttitor faucibus. Aliquam erat volutpat. Mauris euismod pellentesque rutrum. Etiam nec consequat diam. Vivamus aliquet ornare ligula. Praesent nec sagittis sapien, vitae convallis massa. Praesent eu convallis magna, non interdum leo. Praesent dui lacus, tempus eget tellus id, rhoncus rutrum magna. Vivamus augue odio, vulputate ut dapibus blandit, iaculis non mi."),
    new News("Attention Grabber",
        "Suspendisse potenti. Nunc lacus dui, consequat ut libero sed, iaculis commodo velit. Nunc porttitor quam non metus ultrices, a mattis sem efficitur. Praesent nec sem magna. Mauris commodo erat quis rhoncus venenatis. Maecenas urna tortor, consectetur id est ut, pulvinar vulputate urna. Fusce at condimentum diam, ac scelerisque libero. Pellentesque dictum neque at arcu laoreet, vitae suscipit dolor rhoncus. Fusce ligula est, interdum nec finibus ac, tincidunt nec massa. Vestibulum vitae leo felis. Suspendisse dui nulla, condimentum id faucibus sed, feugiat at massa. Duis in mauris arcu. Sed luctus justo ut est tempor mollis. In augue ligula, consectetur nec interdum vel, convallis quis tortor. Curabitur lobortis neque non porttitor faucibus. Aliquam erat volutpat. Mauris euismod pellentesque rutrum. Etiam nec consequat diam. Vivamus aliquet ornare ligula. Praesent nec sagittis sapien, vitae convallis massa. Praesent eu convallis magna, non interdum leo. Praesent dui lacus, tempus eget tellus id, rhoncus rutrum magna. Vivamus augue odio, vulputate ut dapibus blandit, iaculis non mi."),
    new News("Intriguing Statement",
        "Suspendisse potenti. Nunc lacus dui, consequat ut libero sed, iaculis commodo velit. Nunc porttitor quam non metus ultrices, a mattis sem efficitur. Praesent nec sem magna. Mauris commodo erat quis rhoncus venenatis. Maecenas urna tortor, consectetur id est ut, pulvinar vulputate urna. Fusce at condimentum diam, ac scelerisque libero. Pellentesque dictum neque at arcu laoreet, vitae suscipit dolor rhoncus. Fusce ligula est, interdum nec finibus ac, tincidunt nec massa. Vestibulum vitae leo felis. Suspendisse dui nulla, condimentum id faucibus sed, feugiat at massa. Duis in mauris arcu. Sed luctus justo ut est tempor mollis. In augue ligula, consectetur nec interdum vel, convallis quis tortor. Curabitur lobortis neque non porttitor faucibus. Aliquam erat volutpat. Mauris euismod pellentesque rutrum. Etiam nec consequat diam. Vivamus aliquet ornare ligula. Praesent nec sagittis sapien, vitae convallis massa. Praesent eu convallis magna, non interdum leo. Praesent dui lacus, tempus eget tellus id, rhoncus rutrum magna. Vivamus augue odio, vulputate ut dapibus blandit, iaculis non mi."),
    new News("Unignorable Sentence",
        "Suspendisse potenti. Nunc lacus dui, consequat ut libero sed, iaculis commodo velit. Nunc porttitor quam non metus ultrices, a mattis sem efficitur. Praesent nec sem magna. Mauris commodo erat quis rhoncus venenatis. Maecenas urna tortor, consectetur id est ut, pulvinar vulputate urna. Fusce at condimentum diam, ac scelerisque libero. Pellentesque dictum neque at arcu laoreet, vitae suscipit dolor rhoncus. Fusce ligula est, interdum nec finibus ac, tincidunt nec massa. Vestibulum vitae leo felis. Suspendisse dui nulla, condimentum id faucibus sed, feugiat at massa. Duis in mauris arcu. Sed luctus justo ut est tempor mollis. In augue ligula, consectetur nec interdum vel, convallis quis tortor. Curabitur lobortis neque non porttitor faucibus. Aliquam erat volutpat. Mauris euismod pellentesque rutrum. Etiam nec consequat diam. Vivamus aliquet ornare ligula. Praesent nec sagittis sapien, vitae convallis massa. Praesent eu convallis magna, non interdum leo. Praesent dui lacus, tempus eget tellus id, rhoncus rutrum magna. Vivamus augue odio, vulputate ut dapibus blandit, iaculis non mi."),
  ];